run:
  deadline: 10m
  tests: false
#  skip-dirs:
#    - ent

linters-settings:
  golint:
    min-confidence: 0
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude: errcheck_excludes.txt
  gocritic:
    enabled-checks:
      - appendAssign
      - underef
      - yodaStyleExpr
  depguard:
    list-type: blacklist
    include-go-root: false
    #    packages:
    #      - github.com/satori/go.uuid
    packages-with-error-message:
      # specify an error message to output when a blacklisted package is used
      - 'github.com/satori/go.uuid': "use github.com/google/uuid instead"
      # - 'github.com/gofrs/go.uuid': "use github.com/google/uuid instead"
      - 'gopkg.in/yaml.v2': "use gopkg.in/yaml.v3 instead"
      - 'golang.org/x/net/context': "use context instead"

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - typecheck
    - staticcheck
    - gas
    - ineffassign
    - gosimple
    - gocritic
#    - maligned
    - depguard
    # NOTE(timonwong) 错误太特么多了，因此暂时关闭了 golint, errcheck 之后请打开
    - golint    # 这个有点变态, 酌情开启
#     - varcheck  # 一般不用开, 检查 unused var
    - errcheck
    - scopelint

    - goconst
    - structcheck
    - bodyclose
    - rowserrcheck
    - unconvert

issues:
  exclude-rules:
    - text: "G102: Binds to all network interfaces"
      linters:
        - gosec
    - text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
      linters:
        - gosec
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: 'G404: Use of weak random number generator \(math/rand instead of crypto/rand\)'
      linters:
        - gosec
    - text: " should be of the form "
      linters:
        - golint
    - text: '`.+` should be `.+`'
      linters:
        - golint
    - text: '(func|method) \w+ should be \w+'
      linters:
        - golint
    - text: 'type name will be used as .+ by other packages, and that stutters'
      linters:
        - golint
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: 'error strings should not be capitalized or end with punctuation or a newline'
      linters:
        - golint
